/* Named martial repertoires. Action/VFX choreography is an original film adaptation. */
(function(r,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else r.H3_SKILL_CATALOG=api;})(globalThis,function(){
'use strict';
const dragon=[
['亢龙有悔','沉胯弓步，右掌回收至肋下，左掌探中线','后足蹬地、转腰送肩，单掌向目标胸线推出，肘不过伸','金色龙首沿掌心轴线生长，龙脊分三层展开',1.35,.3,.72,'single','line'],
['飞龙在天','腾空后屈膝收掌，俯视目标并对齐下落线路','空中展胯压肩，双掌沿斜下方向轰向目标','龙形气劲从掌缘盘出，沿俯冲线伸展',1.1,.32,.8,'single','line'],
['见龙在田','横移半步立马，前臂收在胸前形成护线','前掌截住攻击线，后掌从中线推出','横向薄金气墙收束为掌前龙鳞屏',.9,.25,.6,'area','cone'],
['鸿渐于陆','前脚试探落点，双掌一前一后收拢','跨步送掌，后掌跟进将气劲递向前方','龙尾贴地拖出金色细沙轨迹',1.0,.26,.65,'single','line'],
['潜龙勿用','屈膝含胸，双掌藏于腰肋不提前外放','身体由低位转起，掌根由下向前挑送','暗金气旋从掌根逐层亮起，出掌才显龙形',1.2,.24,.7,'single','line'],
['利涉大川','大步跨前，后脚蓄蹬，双掌向后收成弧','重心随步贯穿，双掌平推出长距离攻击线','两道金色气流汇成过水长桥般的龙脊',1.4,.3,.8,'area','line'],
['尺蠖之屈','缩身退半步，肘贴肋，掌力内敛','先让开正面来势，再蹬地伸身递掌反击','收缩金环沿前臂滑到掌根，发力时展开',.85,.22,.58,'single','line'],
['或跃在渊','跳起后在低空缩腹提掌，观察敌方抬头动作','调整空中方向后交替递掌，不在原地重复起跳','两条短龙弧先收后展，照亮衣摆下缘',1.0,.3,.72,'single','line'],
['双龙取水','双掌分别收于两肋，前脚稳定攻击轴','双臂沿不同弧线合拢，将两股掌劲送向同一目标','左右两股金龙气劲分离成形，在目标前交汇',1.3,.38,.8,'single','line'],
['神龙摆尾','转马侧身，后掌沿腰肋蓄势，先确认侧方目标','转腰带肩，反掌沿侧向弧线甩出并回护','金色龙尾随掌弧展开，粒子沿切线散开',.95,.32,.7,'area','cone'],
['突如其来','小幅收掌，前足贴地抢进，目标仍在正面','短促蹬步送掌，发力后立即回收护脸','紧凑龙首在掌前瞬间凝成，不提前铺满画面',.6,.2,.55,'single','line'],
['时乘六龙','双掌轮转收拢六股气流，脚步缓慢换位','沿目标扇区分层推出龙形掌劲，主次束有明确方向','六股金龙气流分层展开，白金核心与暗金龙鳞相衬',1.8,.55,1.05,'area','cone'],
['密云不雨','双掌环抱蓄势，气机集中在掌前而不提前释放','拨开对方攻击线后向正面推出凝实掌劲','金色细粒聚成暗云状掌团，释放时亮出龙首',1.5,.3,.85,'single','line'],
['损则有孚','让出半步、沉肩护中线，将来势引向身侧','先卸力后以侧掌递回敌方空门，保留退路','暗金薄膜受压后回弹成短促龙弧',.9,.25,.65,'single','line'],
['龙战于野','宽马步立稳，双掌向两侧开合收气','转腰连续换向，向正面敌群扇区推出掌劲','交错龙脊在正面扇区展开，背后不产生伤害光环',1.6,.5,.95,'area','cone'],
['履霜冰至','重心缓沉，掌缘贴下线蓄势，前脚稳住地面','低掌沿地面向目标下盘推出，再回掌护上段','冷白金霜粒沿低位气浪爬行，勾出细龙鳞纹',1.25,.3,.8,'area','line'],
['羝羊触藩','弓步顶肩，掌根收肋，识别前方障碍与目标','双掌叠力沿单一轴线前推，不把身体撞入对方','坚实金色龙首撞向前方，鳞片粒子在接触处破碎',1.45,.32,.9,'single','line'],
['震惊百里','深马步聚气，双掌从下向胸前托起，留出完整蓄力','双掌前推，主冲击沿目标方向展开并回收重心','白金龙首先破空，后续金环沿前方锥形传开',2.1,.55,1.2,'area','cone']
];
const hands=[
['摊','前臂外旋掌心向上，肘下沉将来拳引至外侧','parry','mid'],['膀','抬肘转肩形成斜桥，前臂贴住来势不硬顶','parry','high'],['伏','腕部下扣贴住对方前臂，肘留在中线限制进路','trap','arm'],['枕','前臂向下沉落接住来势，肩不抬起','parry','mid'],['窒','腕臂短促下压阻住对手续进，同时护住胸线','trap','arm'],['耕','上下手分层护线，下手斜压对方低位攻击','parry','low'],['滚','肘贴肋转腕滚桥，顺着接触点换到来势外侧','parry','arm'],['圈','腕部绕接触点画小圈，转至对手防线空隙','trap','arm'],['穿','前臂沿两臂间隙穿入，掌指仍对准中线','strike','mid'],['批','手掌斜向拍压对方前臂，后手保持护脸','parry','arm'],['搭','前手轻搭来臂读取方向，保持可退的接触','probe','arm'],['截','前臂切入攻击线路，截住来手而不追手远离中线','parry','arm'],['沉','沉肩坠肘压低接触点，身体随转马卸力','trap','arm'],['标','指掌沿防线空隙标出，收回时仍护住面门','strike','high'],['黏','保持前臂接触，随来势微调肘与重心','trap','arm'],['摸','轻触对方桥手确认空门，前脚朝向目标','probe','arm'],['荡','前臂小幅摆荡移开来桥，后手不离中线','parry','arm'],['捋','沿来臂牵引至侧肋，配合转马让开正面','trap','arm']
];
const forms=[];
function step(zh,act,limb,target,t,note,dmg){return {zh,act,limb,target,t,dmg:dmg??(['strike','finish'].includes(act)?1:0),note};}
dragon.forEach((d,i)=>forms.push({key:'xl_'+String(i+1).padStart(2,'0'),zh:d[0],en:'Dragon palm '+(i+1),family:'降龙十八掌',style:'降龙十八掌',category:'法术',tiers:[5,9],weapons:[],range:[3,18],band:'mid',requiresAir:[1,7].includes(i),targeting:{mode:d[7],shape:d[8],range:18,radius:d[7]==='area'?3:0,angle:d[8]==='cone'?65:12,maxTargets:d[7]==='area'?8:1,friendlyFire:false},timing:{charge:[d[4],d[4]+.35],active:[d[5],d[5]+.08],recover:[d[6],d[6]+.15],travel:[.45,1.3],gap:.35,cooldown:2.4},prep:d[1],act:d[2],fx:{shape:d[3],growth:d[3],form:d[8]==='cone'?'dragon-cone':'dragon-line',palette:['金色','白金核心','暗金鳞片'],light:'掌心光照亮前臂与侧脸，龙身沿途在地面投出移动光带，接触处短促亮起后回色',particles:'掌缘细金屑沿气劲方向拖尾；命中时鳞片碎光与现场尘土沿作用线散开；未命中则散入空气',contact:'以实际接触点生成龙鳞碎光和气浪，人物受击幅度以结算为准',miss:'龙形沿原弹道掠过后逐节褪色，不在敌人身上产生爆点',sound:'衣袖翻动、气劲低鸣、释放破风声；接触声仅在实际命中时出现'},steps:[step('立架定位','move','全身','mid',[.18,.06,.14],d[1]),step('凝劲蓄掌','probe','双掌','mid',[d[4],.06,.14],'掌力逐层聚集，保持朝向目标，未完成蓄力不出掌'),step(d[0],'strike','双掌','mid',[.16,d[5],.2],d[2]),step('回掌复位','parry','双掌','mid',[.12,.08,d[6]],'掌势回收，重心归位，经过收招与间隔后才可再次释放')],note:'影视动作编排版；先建立起势与攻击方向，命中、打空、格挡分别结算。'}));
hands.forEach((d,i)=>forms.push({key:'wc_hand_'+String(i+1).padStart(2,'0'),zh:d[0]+'手中线组合',en:'Wing Chun hand chain '+(i+1),family:'咏春',style:'咏春',category:'拳脚',tiers:[1,9],weapons:[],range:[.6,1.5],band:d[3],principles:['中线','朝面追形','来留去送','甩手直冲'],steps:[step(d[0]+'手接桥',d[2],'前手',d[3],[.16,.08,.14],d[1]),step('转马朝面','move','全身','mid',[.12,.06,.1],'脚步小幅调角，胸线仍朝目标，后手护住面门'),step(i%3===0?'日字冲拳':i%3===1?'掌根直击':'连消带打','strike','后手',i%2?'mid':'high',[.15,.08,.18],i%3===0?'拳沿胸口中线直出，腕肘不外张，出后即收':i%3===1?'后掌沿空门向目标胸线推出，肩胯同时送劲':'前手引开来桥，后拳沿空门递进，不盲目追手'),step('留桥回护','parry','双手','mid',[.12,.07,.2],'保留有效接触；对方撤手时收桥直冲，空门关闭时回到护架')],note:'电影组合而非固定武术教学顺序；接桥、步法、打击与回护分段执行。'}));
const extra=[['六脉神剑',['少商剑','商阳剑','中冲剑','关冲剑','少冲剑','少泽剑'],'指端剑气'],['形意五行',['劈拳','崩拳','钻拳','炮拳','横拳'],'肩胯整劲'],['太极八法',['掤','捋','挤','按','采','挒','肘','靠'],'化引接发'],['八极八大招',['顶心肘','猛虎硬爬山','迎门三不顾','霸王硬折缰','左右硬开门','黄莺双抱爪','朝阳手','立地通天炮'],'贴身整劲']];
extra.forEach(([family,names,motif],fi)=>names.forEach((zh,i)=>{const spell=fi===0;forms.push({key:'set_'+fi+'_'+i,zh, en:family+' '+(i+1),family,style:family,category:spell?'法术':'拳脚',tiers:spell?[5,9]:[1,9],weapons:[],range:spell?[3,15]:[.6,1.8],band:i%2?'high':'mid',timing:spell?{charge:[.75,1.15],active:[.16,.24],recover:[.5,.7],travel:[.25,.7],gap:.25,cooldown:1.6}:undefined,targeting:spell?{mode:'single',shape:'line',range:15,radius:0,angle:8,maxTargets:1}:undefined,prep:'侧身护架，前脚对齐目标，'+motif+'收于腰肋',act:spell?'对应指端伸出，沿锁定的攻击线送出细束剑气':'先接住来势，配合转胯向目标空门递出'+zh,fx:spell?{form:'finger-beam',palette:['冷白','淡青'],light:'指尖冷光照亮手背，细束剑气在目标前形成窄光线',particles:'指端细光点沿直线流动，接触处迸出小簇白屑',contact:'实际接触点亮起窄小剑气碎光',miss:'细束按原线路飞空后消散',sound:'短促指端破风声，命中才有接触声'}:undefined,steps:[step('立架辨线','probe','前手','mid',[.15,.07,.12],'朝面追形，观察来势与空门'),step('引桥换位','parry','前手','arm',[.16,.08,.15],'避开正面线路并引桥，重心不浮起'),step(zh,'strike',spell?'手指':fi===3&&i===0?'肘':'后手',i%2?'high':'mid',[.18,.1,.22],spell?'指端凝气，沿目标方向放出细束':'肩胯配合递出'+zh+'，作用线落在目标空门'),step('归架待机','parry','双手','mid',[.12,.08,.22],'完整收势，恢复视线和距离后再选后手')],note:'具名影视组合，具体动作与时序为本程序编排。'});}));
const families=[{name:'降龙十八掌',forms:forms.filter(x=>x.family==='降龙十八掌').map(x=>x.key),combos:[{name:'守线反击',forms:['xl_03','xl_07','xl_01'],condition:'拦下正面来势后，目标仍在前方射程内'},{name:'空中追击',forms:['xl_02','xl_08','xl_09'],condition:'已腾空且目标可见；落地或体力不足时终止'},{name:'侧破围攻',forms:['xl_10','xl_15','xl_18'],condition:'多名敌人在前方有效扇区，收招后再递后掌'}]},...['咏春',...extra.map(x=>x[0])].map(name=>({name,forms:forms.filter(x=>x.family===name).map(x=>x.key),combos:[{name:'接桥换位进击',forms:forms.filter(x=>x.family===name).slice(0,3).map(x=>x.key),condition:'空门持续且距离允许；失去接触或目标改变时重新选招'}]}))];
function get(name){return forms.find(x=>x.key===name||x.zh===name)||null;}
function repertoire(name){return families.find(f=>String(name||'').includes(f.name))||null;}
function select(name,cursor=0,air=false){const one=get(name);if(one)return one.requiresAir&&!air?null:one;const family=repertoire(name);if(!family)return null;const list=family.forms.map(get).filter(x=>!x.requiresAir||air);return list[Math.abs(cursor)%list.length]||null;}
function fxDescription(f,outcome='release'){if(!f?.fx)return '';return ['【'+f.zh+'】'+f.prep+' → '+f.act,'形态：'+(f.fx.growth||f.fx.shape||f.fx.form),'光影：'+f.fx.light,'粒子：'+f.fx.particles,outcome==='hit'?'命中：'+f.fx.contact:outcome==='miss'?'打空：'+f.fx.miss:'释放后沿真实攻击线飞行，命中效果仅在接触时出现','声音：'+f.fx.sound].join('；');}
function targets(origin,all,profile,team){const p=profile||{mode:'single',range:1.5};return (all||[]).filter(t=>t.hp>0&&t.id!==origin.id&&(p.friendlyFire||t.team!==team)).map(t=>({t,d:Math.hypot(t.x-origin.x,t.y-origin.y),a:Math.abs(Math.atan2(Math.sin(Math.atan2(t.y-origin.y,t.x-origin.x)-(origin.face||0)),Math.cos(Math.atan2(t.y-origin.y,t.x-origin.x)-(origin.face||0))))})).filter(x=>x.d<=p.range&&((p.shape==='circle')||(x.a<=(p.angle||20)*Math.PI/360))).sort((a,b)=>a.d-b.d).slice(0,p.mode==='area'?(p.maxTargets||8):1).map(x=>x.t);}
return {VERSION:'skill-catalog-1.0',forms,families,hands,get,repertoire,select,fxDescription,targets};});
