/* ============================================================================
 * templates/corpus-data.js — 【生成文件，请勿手改】
 *   由 `node templates/corpus-build.js` 从本地采集语料生成。
 *   内容：公开成片提示词的**结构化索引**（标题/题材/结构/时长/作者/出处/结构性事实）。
 *   许可：BeatAPI Prompt Gallery 的文档为 CC BY 4.0（署名：BeatAPI Prompt Gallery ＋ 仓库链接）；
 *         第三方提示词**未由该仓库再许可**，故本文件**不含提示词原文**，原文仅存于本地
 *         _template_sources/ 供人工核对，出处链接逐条给出。
 *   生成时间与来源统计：见文件末尾 SUMMARY。
 * ========================================================================== */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.TPL_CORPUS_DATA = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const META = {
  "version": "corpus-data-0.1",
  "generatedBy": "templates/corpus-build.js",
  "generatedAt": "2026-09-21",
  "sourceRepo": "https://github.com/BeatAPI/awesome-minimax-h3-prompts",
  "docLicense": "CC BY 4.0（署名：BeatAPI Prompt Gallery）",
  "thirdPartyNote": "第三方提示词未由该仓库再许可；本文件不含提示词原文，只含结构化索引与出处链接。",
  "scanned": 329,
  "kept": 47
};
  const ROWS = [
 {
  "slug": "style-hyper-realistic-dark-fantasy-tavern-cinematic-gro-137433",
  "slugLabel": "style hyper realistic dark fantasy tavern cinematic gro",
  "titleFromSlug": false,
  "titleZh": "暗黑奇幻酒馆斗殴",
  "titleEn": "Dark-Fantasy Tavern Fight",
  "genre": "anime_action",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "anime",
  "author": "@craftian_keskin",
  "sourceUrl": "https://x.com/craftian_keskin/status/2082658222247137433",
  "sourceKind": "x",
  "promptLength": 3398,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "sword",
   "blade",
   "axe"
  ],
  "keywords": [
   "fight",
   "battle",
   "combat",
   "sword",
   "blade",
   "axe",
   "punch",
   "strike"
  ],
  "fightScore": 12
 },
 {
  "slug": "urban-street-superpowered-punch-action-sequence-712509",
  "slugLabel": "urban street superpowered punch action sequence",
  "titleFromSlug": false,
  "titleZh": "都市街头超能力重拳动作",
  "titleEn": "Urban street superpowered punch action sequence",
  "genre": "superhero",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "28s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@itsshara_ai",
  "sourceUrl": "https://x.com/itsshara_ai/status/2082892924694712509",
  "sourceKind": "x",
  "promptLength": 7088,
  "hasPartBlocks": true,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "whip",
   "fist"
  ],
  "keywords": [
   "fight",
   "combat",
   "explosion",
   "punch",
   "kick",
   "grapple",
   "arena",
   "superpower"
  ],
  "fightScore": 12
 },
 {
  "slug": "which-one-looks-better-to-you-565341",
  "slugLabel": "which one looks better to you",
  "titleFromSlug": false,
  "titleZh": "Which one looks better to you?",
  "titleEn": "Which one looks better to you?",
  "genre": "beast",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "4:5",
  "category": "music-video",
  "author": "@KrevixAi",
  "sourceUrl": "https://x.com/KrevixAi/status/2085759071047565341",
  "sourceKind": "x",
  "promptLength": 6354,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "blade",
   "spear",
   "axe",
   "shield",
   "hammer"
  ],
  "keywords": [
   "battle",
   "combat",
   "blade",
   "spear",
   "axe",
   "kick",
   "strike",
   "magic"
  ],
  "fightScore": 12
 },
 {
  "slug": "15-second-16-9-photoreal-cinematic-action-sequence-with-743096",
  "slugLabel": "15 second 16 9 photoreal cinematic action sequence with",
  "titleFromSlug": false,
  "titleZh": "沙漠越野车战斗追逐",
  "titleEn": "Desert Buggy Combat Chase",
  "genre": "chase",
  "structure": "breakout",
  "structureGuessed": false,
  "duration": "21s",
  "mode": "reference-to-video",
  "aspectRatio": "637:270",
  "category": "horror",
  "author": "@beginnersblog1",
  "sourceUrl": "https://x.com/beginnersblog1/status/2083039412506743096",
  "sourceKind": "x",
  "promptLength": 6412,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "combat",
   "explosion",
   "magic",
   "mecha",
   "giant",
   "chase",
   "pursuit"
  ],
  "fightScore": 11
 },
 {
  "slug": "15-second-cinematic-showdown-between-the-most-technolog-354071",
  "slugLabel": "15 second cinematic showdown between the most technolog",
  "titleFromSlug": false,
  "titleZh": "赛博战士对决远古斗士",
  "titleEn": "Cyber Warrior vs. Primordial Fighter",
  "genre": "scifi_mecha",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "action",
  "author": "@alex_bagnuoli89",
  "sourceUrl": "https://x.com/alex_bagnuoli89/status/2083207597025354071",
  "sourceKind": "x",
  "promptLength": 1982,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "blade"
  ],
  "keywords": [
   "fight",
   "battle",
   "showdown",
   "blade",
   "explosion",
   "warrior"
  ],
  "fightScore": 10
 },
 {
  "slug": "no-moon-restoration-yet-834347",
  "slugLabel": "no moon restoration yet",
  "titleFromSlug": true,
  "titleZh": "",
  "titleEn": "",
  "genre": "beast",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086321924070834347",
  "sourceKind": "x",
  "promptLength": 24813,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe"
  ],
  "keywords": [
   "fight",
   "combat",
   "axe",
   "explosion",
   "sect",
   "magic",
   "dragon",
   "giant"
  ],
  "fightScore": 10
 },
 {
  "slug": "seamless-warrior-sword-reflection-loop-874724",
  "slugLabel": "seamless warrior sword reflection loop",
  "titleFromSlug": false,
  "titleZh": "武士剑影无缝循环",
  "titleEn": "Seamless Warrior Sword Reflection Loop",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "30s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "fashion",
  "author": "@Cia0_exe",
  "sourceUrl": "https://x.com/Cia0_exe/status/2082774526098874724",
  "sourceKind": "x",
  "promptLength": 6953,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "sword",
   "blade"
  ],
  "keywords": [
   "sword",
   "blade",
   "kick",
   "strike",
   "spell",
   "warrior"
  ],
  "fightScore": 10
 },
 {
  "slug": "storm-lit-pirate-galleon-battle-561048",
  "slugLabel": "storm lit pirate galleon battle",
  "titleFromSlug": false,
  "titleZh": "风暴闪电下的海盗帆船大战",
  "titleEn": "Storm-Lit Pirate Galleon Battle",
  "genre": "gunfight",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "10s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "action",
  "author": "@seirdotmk",
  "sourceUrl": "https://x.com/seirdotmk/status/2083582886280561048",
  "sourceKind": "x",
  "promptLength": 3404,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "blade",
   "pistol",
   "cannon"
  ],
  "keywords": [
   "fight",
   "duel",
   "battle",
   "combat",
   "clash",
   "melee",
   "blade",
   "pistol"
  ],
  "fightScore": 10
 },
 {
  "slug": "first-storyboard-image-to-video-using-s-minimax-h3-on-105162",
  "slugLabel": "first storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "First Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "First Storyboard Image to video using 's MiniMax H3 on",
  "genre": "magic",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086321605073105162",
  "sourceKind": "x",
  "promptLength": 24378,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "combat",
   "explosion",
   "sect",
   "magic",
   "dragon",
   "giant",
   "chase",
   "pursuit"
  ],
  "fightScore": 9
 },
 {
  "slug": "no-painful-reactions-707867",
  "slugLabel": "no painful reactions",
  "titleFromSlug": false,
  "titleZh": "No painful reactions.",
  "titleEn": "No painful reactions.",
  "genre": "magic",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086322454679707867",
  "sourceKind": "x",
  "promptLength": 24735,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "explosion",
   "sect",
   "spell",
   "magic",
   "mecha",
   "dragon",
   "giant",
   "superhero"
  ],
  "fightScore": 9
 },
 {
  "slug": "create-a-15-second-ultra-photorealistic-live-action-war-sequence-714552",
  "slugLabel": "create a 15 second ultra photorealistic live action war",
  "titleFromSlug": true,
  "titleZh": "",
  "titleEn": "",
  "genre": "gunfight",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "music-video",
  "author": "@RuzainaMeer",
  "sourceUrl": "https://x.com/RuzainaMeer/status/2087117707816714552",
  "sourceKind": "x",
  "promptLength": 3119,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "gun"
  ],
  "keywords": [
   "combat",
   "explosion",
   "mecha",
   "superhero",
   "soldier",
   "war "
  ],
  "fightScore": 8
 },
 {
  "slug": "mechanical-bull-charge-the-beasts-are-coming-720815",
  "slugLabel": "mechanical bull charge the beasts are coming",
  "titleFromSlug": false,
  "titleZh": "机械公牛冲锋·野兽将至",
  "titleEn": "Mechanical bull charge The Beasts Are Coming",
  "genre": "beast",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@rahulnanda86",
  "sourceUrl": "https://x.com/rahulnanda86/status/2083033635364720815",
  "sourceKind": "x",
  "promptLength": 2261,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "battle",
   "mecha",
   "beast",
   "giant"
  ],
  "fightScore": 8
 },
 {
  "slug": "seamless-loop-cinematic-warrior-blade-reconstruction-513162",
  "slugLabel": "seamless loop cinematic warrior blade reconstruction",
  "titleFromSlug": false,
  "titleZh": "无缝循环武士刀刃重构",
  "titleEn": "Seamless-loop cinematic warrior blade reconstruction",
  "genre": "gunfight",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "image-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@ogbenniasamuel2",
  "sourceUrl": "https://x.com/ogbenniasamuel2/status/2082934406910513162",
  "sourceKind": "x",
  "promptLength": 5826,
  "hasPartBlocks": false,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "sword",
   "blade"
  ],
  "keywords": [
   "sword",
   "blade",
   "kick",
   "warrior"
  ],
  "fightScore": 8
 },
 {
  "slug": "start-and-end-images-in-minimax-h3-comfyui-785340",
  "slugLabel": "start and end images in minimax h3 comfyui",
  "titleFromSlug": false,
  "titleZh": "Start and End Images in Minimax H3 Comfyui...",
  "titleEn": "Start and End Images in Minimax H3 Comfyui...",
  "genre": "ancient_war",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "8s",
  "mode": "text-to-video",
  "aspectRatio": "43:24",
  "category": "music-video",
  "author": "@EndFolding79421",
  "sourceUrl": "https://x.com/EndFolding79421/status/2088060516027785340",
  "sourceKind": "x",
  "promptLength": 8897,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": true,
  "weapons": [
   "spear",
   "axe",
   "shield"
  ],
  "keywords": [
   "fight",
   "battle",
   "spear",
   "axe",
   "mecha",
   "warrior",
   "soldier"
  ],
  "fightScore": 7
 },
 {
  "slug": "tested-minimax-h3-for-the-first-time-with-a-scene-784843",
  "slugLabel": "tested minimax h3 for the first time with a",
  "titleFromSlug": false,
  "titleZh": "Tested MiniMax H3 for the first time with a scene like this",
  "titleEn": "Tested MiniMax H3 for the first time with a scene like this",
  "genre": "beast",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "action",
  "author": "@RuzainaMeer",
  "sourceUrl": "https://x.com/RuzainaMeer/status/2085240792067784843",
  "sourceKind": "x",
  "promptLength": 768,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "battle",
   "combat",
   "explosion",
   "strike",
   "monster",
   "giant",
   "warrior"
  ],
  "fightScore": 7
 },
 {
  "slug": "wake-up-we-hunt-mechanical-bull-mount-700581",
  "slugLabel": "wake up we hunt mechanical bull mount",
  "titleFromSlug": false,
  "titleZh": "醒来，我们去狩猎",
  "titleEn": "Wake up We Hunt mechanical bull mount",
  "genre": "scifi_mecha",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@rahulnanda86",
  "sourceUrl": "https://x.com/rahulnanda86/status/2083032575908700581",
  "sourceKind": "x",
  "promptLength": 1856,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "battle",
   "mecha",
   "titan",
   "beast",
   "giant"
  ],
  "fightScore": 7
 },
 {
  "slug": "first-storyboard-image-to-video-using-s-minimax-h3-on-333283",
  "slugLabel": "first storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "First Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "First Storyboard Image to video using 's MiniMax H3 on",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086050663365333283",
  "sourceKind": "x",
  "promptLength": 24652,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe"
  ],
  "keywords": [
   "axe",
   "explosion",
   "sect",
   "magic",
   "giant",
   "superhero"
  ],
  "fightScore": 6
 },
 {
  "slug": "first-storyboard-image-to-video-using-s-minimax-h3-on-517354",
  "slugLabel": "first storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "First Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "First Storyboard Image to video using 's MiniMax H3 on",
  "genre": "beast",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2087065646903517354",
  "sourceKind": "x",
  "promptLength": 24769,
  "hasPartBlocks": true,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "bow"
  ],
  "keywords": [
   "axe",
   "explosion",
   "sect",
   "magic",
   "giant",
   "chase"
  ],
  "fightScore": 6
 },
 {
  "slug": "fourthi-storyboard-image-to-video-using-minimax-h3-on-470161",
  "slugLabel": "fourthi storyboard image to video using minimax h3 on",
  "titleFromSlug": false,
  "titleZh": "Fourthi Storyboard Image to video using MiniMax H3 on",
  "titleEn": "Fourthi Storyboard Image to video using MiniMax H3 on",
  "genre": "magic",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086323087092470161",
  "sourceKind": "x",
  "promptLength": 24793,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "shield"
  ],
  "keywords": [
   "axe",
   "explosion",
   "sect",
   "magic",
   "dragon",
   "giant"
  ],
  "fightScore": 6
 },
 {
  "slug": "generated-with-minimax-h3-on-116099",
  "slugLabel": "generated with minimax h3 on",
  "titleFromSlug": false,
  "titleZh": "Generated with Minimax H3 on",
  "titleEn": "Generated with Minimax H3 on",
  "genre": "ancient_war",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "music-video",
  "author": "@Diplomeme",
  "sourceUrl": "https://x.com/Diplomeme/status/2086833428713116099",
  "sourceKind": "x",
  "promptLength": 2380,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "spear",
   "shield"
  ],
  "keywords": [
   "battle",
   "spear",
   "dragon",
   "giant",
   "warrior",
   "soldier"
  ],
  "fightScore": 6
 },
 {
  "slug": "image-1-for-the-character-image-2-for-the-619967",
  "slugLabel": "image 1 for the character image 2 for the",
  "titleFromSlug": false,
  "titleZh": "彩色颜料武器选择界面",
  "titleEn": "Colorful Paint-Weapon Selection Screen",
  "genre": "gunfight",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "gameplay",
  "author": "@craftian_keskin",
  "sourceUrl": "https://x.com/craftian_keskin/status/2082893990995619967",
  "sourceKind": "x",
  "promptLength": 3103,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "rifle",
   "pistol",
   "gun",
   "cannon"
  ],
  "keywords": [
   "axe",
   "sniper",
   "rifle",
   "pistol",
   "mecha",
   "giant"
  ],
  "fightScore": 6
 },
 {
  "slug": "minimax-h3-on-v-s-seedance-2-5-783077",
  "slugLabel": "minimax h3 on v s seedance 2 5",
  "titleFromSlug": false,
  "titleZh": "MiniMax H3 on v/s Seedance 2.5",
  "titleEn": "MiniMax H3 on v/s Seedance 2.5",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "music-video",
  "author": "@HeyZoyaKhan",
  "sourceUrl": "https://x.com/HeyZoyaKhan/status/2085575259533783077",
  "sourceKind": "x",
  "promptLength": 1988,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "sword",
   "claw"
  ],
  "keywords": [
   "fight",
   "battle",
   "sword",
   "strike",
   "magic",
   "warrior"
  ],
  "fightScore": 6
 },
 {
  "slug": "modern-warfare-fps-gameplay",
  "slugLabel": "modern warfare fps gameplay",
  "titleFromSlug": false,
  "titleZh": "现代战争 FPS 实机画面",
  "titleEn": "Modern warfare FPS gameplay",
  "genre": "gunfight",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "gameplay",
  "author": "@Just_sharon7",
  "sourceUrl": "https://x.com/Just_sharon7/status/2083064417798025721",
  "sourceKind": "x",
  "promptLength": 3303,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "rifle"
  ],
  "keywords": [
   "fight",
   "battle",
   "firefight",
   "rifle",
   "mecha",
   "soldier"
  ],
  "fightScore": 6
 },
 {
  "slug": "second-storyboard-image-to-video-using-s-minimax-h3-on-647644",
  "slugLabel": "second storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "Second Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "Second Storyboard Image to video using 's MiniMax H3 on",
  "genre": "anime_action",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2085986990919647644",
  "sourceKind": "x",
  "promptLength": 24808,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "bow",
   "whip"
  ],
  "keywords": [
   "axe",
   "magic",
   "robot",
   "demon",
   "giant",
   "villain"
  ],
  "fightScore": 6
 },
 {
  "slug": "storyboard-image-to-video-using-s-minimax-h3-on-693556",
  "slugLabel": "storyboard image to video using s minimax h3 on",
  "titleFromSlug": false,
  "titleZh": "Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "Storyboard Image to video using 's MiniMax H3 on",
  "genre": "chase",
  "structure": "breakout",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2085606945755693556",
  "sourceKind": "x",
  "promptLength": 17263,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "gun"
  ],
  "keywords": [
   "axe",
   "explosion",
   "kick",
   "chase",
   "pursuit",
   "villain"
  ],
  "fightScore": 6
 },
 {
  "slug": "16-9-cinematic-wuxia-mystery-set-in-a-bamboo-571041",
  "slugLabel": "16 9 cinematic wuxia mystery set in a bamboo",
  "titleFromSlug": false,
  "titleZh": "竹林武侠谜案",
  "titleEn": "Bamboo Forest Wuxia Mystery",
  "genre": "wuxia",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@AIwithAliya",
  "sourceUrl": "https://x.com/AIwithAliya/status/2083132770650571041",
  "sourceKind": "x",
  "promptLength": 1116,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "martial",
   "wuxia",
   "sect"
  ],
  "fightScore": 5
 },
 {
  "slug": "created-with-minimax-h3-708458",
  "slugLabel": "created with minimax h3",
  "titleFromSlug": false,
  "titleZh": "Created with MiniMax H3",
  "titleEn": "Created with MiniMax H3",
  "genre": "ancient_war",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "68:45",
  "category": "music-video",
  "author": "@Lianaalane",
  "sourceUrl": "https://x.com/Lianaalane/status/2085625652829708458",
  "sourceKind": "x",
  "promptLength": 3773,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "sword"
  ],
  "keywords": [
   "battle",
   "sword",
   "strike",
   "giant",
   "warrior"
  ],
  "fightScore": 5
 },
 {
  "slug": "hailuo-has-been-great-at-text-motion-graphics-for-a-330229",
  "slugLabel": "hailuo has been great at text motion graphics for",
  "titleFromSlug": false,
  "titleZh": "Hailuo has been great at text motion graphics for a long time, but it really shines with H…",
  "titleEn": "Hailuo has been great at text motion graphics for a long time, but it really shines with H…",
  "genre": "samurai",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "music-video",
  "author": "@opener_ai",
  "sourceUrl": "https://x.com/opener_ai/status/2085159317578330229",
  "sourceKind": "x",
  "promptLength": 2908,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "sword",
   "katana",
   "blade",
   "whip"
  ],
  "keywords": [
   "duel",
   "sword",
   "blade",
   "katana",
   "martial"
  ],
  "fightScore": 5
 },
 {
  "slug": "made-it-on-225758",
  "slugLabel": "made it on",
  "titleFromSlug": false,
  "titleZh": "Made it on",
  "titleEn": "Made it on",
  "genre": "ancient_war",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "1:1",
  "category": "music-video",
  "author": "@MadMax_Series",
  "sourceUrl": "https://x.com/MadMax_Series/status/2083501727836225758",
  "sourceKind": "x",
  "promptLength": 6754,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "battle",
   "strike",
   "dragon",
   "warrior",
   "army"
  ],
  "fightScore": 5
 },
 {
  "slug": "second-storyboard-image-to-video-using-s-minimax-h3-on-495506",
  "slugLabel": "second storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "Second Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "Second Storyboard Image to video using 's MiniMax H3 on",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086294491179495506",
  "sourceKind": "x",
  "promptLength": 24811,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe"
  ],
  "keywords": [
   "axe",
   "explosion",
   "spell",
   "magic",
   "giant"
  ],
  "fightScore": 5
 },
 {
  "slug": "stunning-action-packed-scene-following-a-little-robot-r-288619",
  "slugLabel": "stunning action packed scene following a little robot r",
  "titleFromSlug": false,
  "titleZh": "小机器人赛博朋克逃亡",
  "titleEn": "Little Robot Cyberpunk Escape",
  "genre": "scifi_mecha",
  "structure": "breakout",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@AIandDesign",
  "sourceUrl": "https://x.com/AIandDesign/status/2082522979339288619",
  "sourceKind": "x",
  "promptLength": 354,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "robot",
   "chase",
   "soldier"
  ],
  "fightScore": 5
 },
 {
  "slug": "the-viewer-should-immediately-want-to-see-how-3-200-630916",
  "slugLabel": "the viewer should immediately want to see how 3",
  "titleFromSlug": true,
  "titleZh": "",
  "titleEn": "",
  "genre": "scifi_mecha",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086294164409630916",
  "sourceKind": "x",
  "promptLength": 23241,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "explosion",
   "sect",
   "magic",
   "giant",
   "superhero"
  ],
  "fightScore": 5
 },
 {
  "slug": "3d-pixar-style-animated-comedy-short-film-ultra-premium-057697",
  "slugLabel": "3d pixar style animated comedy short film ultra premium",
  "titleFromSlug": false,
  "titleZh": "厨房巨蛛喜剧短片",
  "titleEn": "Giant Kitchen Spider Comedy Short",
  "genre": "anime_action",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "92:39",
  "category": "anime",
  "author": "@Ciri_ai",
  "sourceUrl": "https://x.com/Ciri_ai/status/2082840410268057697",
  "sourceKind": "x",
  "promptLength": 2936,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "shield"
  ],
  "keywords": [
   "battle",
   "giant"
  ],
  "fightScore": 4
 },
 {
  "slug": "and-reference-preserve-the-rider-s-face-short-curly-375367",
  "slugLabel": "and reference preserve the rider s face short curly",
  "titleFromSlug": false,
  "titleZh": "夜间摩托追逐音乐同步短片",
  "titleEn": "Nighttime Motorcycle Chase Synced to Music",
  "genre": "chase",
  "structure": "breakout",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@HBCoop_",
  "sourceUrl": "https://x.com/HBCoop_/status/2083282581450375367",
  "sourceKind": "x",
  "promptLength": 2081,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "sect",
   "chase"
  ],
  "fightScore": 4
 },
 {
  "slug": "created-with-minimax-h3-243802",
  "slugLabel": "created with minimax h3",
  "titleFromSlug": false,
  "titleZh": "Created with MiniMax H3",
  "titleEn": "Created with MiniMax H3",
  "genre": "ancient_war",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "music-video",
  "author": "@aiwithaly",
  "sourceUrl": "https://x.com/aiwithaly/status/2085585698699243802",
  "sourceKind": "x",
  "promptLength": 876,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "fight",
   "battle",
   "strike",
   "martial"
  ],
  "fightScore": 4
 },
 {
  "slug": "deck-builder-turn-ui-choreography-446745",
  "slugLabel": "deck builder turn ui choreography",
  "titleFromSlug": false,
  "titleZh": "奇幻卡组构筑战斗界面",
  "titleEn": "Fantasy Deck-Builder Battle UI",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "reference-to-video",
  "aspectRatio": "16:9",
  "category": "gameplay",
  "author": "@AllaAisling",
  "sourceUrl": "https://x.com/AllaAisling/status/2082909383424446745",
  "sourceKind": "x",
  "promptLength": 1608,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "battle",
   "spell"
  ],
  "fightScore": 4
 },
 {
  "slug": "fast-paced-15-second-16-9-anime-opening-title-se-734471",
  "slugLabel": "fast paced 15 second 16 9 anime opening title",
  "titleFromSlug": false,
  "titleZh": "动画短片案例 734471",
  "titleEn": "Anime Film Study 734471",
  "genre": "anime_action",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "anime",
  "author": "@aimikoda",
  "sourceUrl": "https://x.com/aimikoda/status/2083611951003734471",
  "sourceKind": "x",
  "promptLength": 4286,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "sword",
   "katana",
   "blade",
   "whip"
  ],
  "keywords": [
   "sword",
   "blade",
   "katana",
   "strike"
  ],
  "fightScore": 4
 },
 {
  "slug": "fire-breathing-dragon-in-broken-palace-831106",
  "slugLabel": "fire breathing dragon in broken palace",
  "titleFromSlug": false,
  "titleZh": "破碎宫殿中的喷火巨龙",
  "titleEn": "Fire-breathing dragon in broken palace",
  "genre": "ancient_war",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "cinematic-story",
  "author": "@dreamydigiarts",
  "sourceUrl": "https://x.com/dreamydigiarts/status/2082745513573831106",
  "sourceKind": "x",
  "promptLength": 1827,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "claw"
  ],
  "keywords": [
   "strike",
   "dragon"
  ],
  "fightScore": 4
 },
 {
  "slug": "first-storyboard-image-to-video-using-s-minimax-h3-on-951530",
  "slugLabel": "first storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "First Storyboard Image to video using 's MiniMax H3 on",
  "titleEn": "First Storyboard Image to video using 's MiniMax H3 on",
  "genre": "beast",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2085986114800951530",
  "sourceKind": "x",
  "promptLength": 23806,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "bow"
  ],
  "keywords": [
   "sect",
   "magic",
   "robot",
   "giant"
  ],
  "fightScore": 4
 },
 {
  "slug": "first-storyboard-image-to-video-using-s-minimax-h3-on-995928",
  "slugLabel": "first storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "First Storyboard image to video using 's MiniMax H3 on",
  "titleEn": "First Storyboard image to video using 's MiniMax H3 on",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086667268700995928",
  "sourceKind": "x",
  "promptLength": 24629,
  "hasPartBlocks": true,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "bow",
   "whip"
  ],
  "keywords": [
   "axe",
   "sect",
   "magic",
   "demon"
  ],
  "fightScore": 4
 },
 {
  "slug": "giant-koi-park-incident",
  "slugLabel": "giant koi park incident",
  "titleFromSlug": false,
  "titleZh": "公园巨型锦鲤意外",
  "titleEn": "Giant koi park incident",
  "genre": "beast",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "viral-short",
  "author": "@underwoodxie96",
  "sourceUrl": "https://x.com/underwoodxie96/status/2082747838782386563",
  "sourceKind": "x",
  "promptLength": 2623,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "strike",
   "giant"
  ],
  "fightScore": 4
 },
 {
  "slug": "player-stats-ui-170293",
  "slugLabel": "player stats ui",
  "titleFromSlug": false,
  "titleZh": "Player stats UI",
  "titleEn": "Player stats UI",
  "genre": "scifi_mecha",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "9:16",
  "category": "cinematic-travel",
  "author": "@adithatipalli",
  "sourceUrl": "https://x.com/adithatipalli/status/2086477914699170293",
  "sourceKind": "x",
  "promptLength": 3985,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "blade"
  ],
  "keywords": [
   "combat",
   "blade",
   "sect",
   "mecha"
  ],
  "fightScore": 4
 },
 {
  "slug": "reference-control-use-the-uploaded-part-2-storyboard-image-for-477564",
  "slugLabel": "reference control use the uploaded part 2 storyboard image",
  "titleFromSlug": true,
  "titleZh": "",
  "titleEn": "",
  "genre": "magic",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086051214425477564",
  "sourceKind": "x",
  "promptLength": 24651,
  "hasPartBlocks": true,
  "hasShotMarkers": true,
  "hasSoundField": false,
  "weapons": [
   "axe"
  ],
  "keywords": [
   "axe",
   "sect",
   "magic",
   "giant"
  ],
  "fightScore": 4
 },
 {
  "slug": "second-storyboard-image-to-video-using-minimax-h3-on-215889",
  "slugLabel": "second storyboard image to video using minimax h3 on",
  "titleFromSlug": false,
  "titleZh": "Second Storyboard Image to video using MiniMax H3 on",
  "titleEn": "Second Storyboard Image to video using MiniMax H3 on",
  "genre": "beast",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086426551114215889",
  "sourceKind": "x",
  "promptLength": 24665,
  "hasPartBlocks": true,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "bow",
   "whip"
  ],
  "keywords": [
   "axe",
   "magic",
   "giant",
   "arena"
  ],
  "fightScore": 4
 },
 {
  "slug": "seocnd-storyboard-image-to-video-using-s-minimax-h3-on-442041",
  "slugLabel": "seocnd storyboard image to video using s minimax h3",
  "titleFromSlug": false,
  "titleZh": "Seocnd Storyboard image to video using 's MiniMax H3 on",
  "titleEn": "Seocnd Storyboard image to video using 's MiniMax H3 on",
  "genre": "beast",
  "structure": "human_vs_beast",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ManuAGI01",
  "sourceUrl": "https://x.com/ManuAGI01/status/2086667788488442041",
  "sourceKind": "x",
  "promptLength": 24738,
  "hasPartBlocks": true,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "axe",
   "bow",
   "whip"
  ],
  "keywords": [
   "axe",
   "magic",
   "demon",
   "giant"
  ],
  "fightScore": 4
 },
 {
  "slug": "t2v-hailuo-minimaxh3-prompt-format-create-a-15-second-16-099381",
  "slugLabel": "t2v hailuo minimaxh3 prompt format create a 15 second",
  "titleFromSlug": true,
  "titleZh": "",
  "titleEn": "",
  "genre": "scifi_mecha",
  "structure": "duel",
  "structureGuessed": false,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "fashion",
  "author": "@opener_ai",
  "sourceUrl": "https://x.com/opener_ai/status/2087042643369099381",
  "sourceKind": "x",
  "promptLength": 4355,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [],
  "keywords": [
   "strike",
   "spell",
   "mecha",
   "giant"
  ],
  "fightScore": 4
 },
 {
  "slug": "try-it-731290",
  "slugLabel": "try it",
  "titleFromSlug": false,
  "titleZh": "Try it →",
  "titleEn": "Try it →",
  "genre": "scifi_mecha",
  "structure": "duel",
  "structureGuessed": true,
  "duration": "15s",
  "mode": "text-to-video",
  "aspectRatio": "16:9",
  "category": "product-commercial",
  "author": "@ImaStudio_ai",
  "sourceUrl": "https://x.com/ImaStudio_ai/status/2096807169945731290",
  "sourceKind": "x",
  "promptLength": 3067,
  "hasPartBlocks": false,
  "hasShotMarkers": false,
  "hasSoundField": false,
  "weapons": [
   "bow"
  ],
  "keywords": [
   "explosion",
   "punch",
   "kick",
   "giant"
  ],
  "fightScore": 4
 }
];
  return { META: META, ROWS: ROWS };
});
